### ISSUE TITLE
Hiding dates and reorder post meta

### ISSUE THREAD

**Issue by spookey** [spookey/slick#3]
I found the fork of @mattt-b - especially [that commit](https://github.com/mattt-b/slick/commit/defd637349941f0a6ef863e3318eef9d9a0c10a0)

---

I think it is a valid requirement to have some ability to hide the post dates.
But now I am wondering what would be the best solution for that.
I see two possibilities:

- Keep the option ``dateFmt`` like it is (displaying some fallback value if not set) and introduce another config option (e.g. ``showPostDates``) where the display of dates can be controlled.

- Use the existing ``dateFmt`` value but instead of displaying some fallback if not set, completely hide the date.

---

Second topic: I think it is also some valid requirement to control the display order of the taxonomies in the post meta.

Currently I am struggling very much to read the Taxonomies in a proper form.
If I use ``$.Site.Taxonomies`` the Result is a [TaxonomyList](https://godoc.org/github.com/gohugoio/hugo/hugolib#TaxonomyList). 
But it is defined like this:

```
type TaxonomyList map[string]Taxonomy
```
My expectation was, that the map is at least in the order of how it is defined in the config - but it is always alphabetically, sorted by value.
Does anyone know I can [get rid of this construct](https://github.com/spookey/slick/blob/b0ced637cf093a544f290332a482decb030d4b2e/layouts/partials/post_meta.html#L7) and solve it in a more flexible way?

---

If anyone has some ideas or opinions - please feel free to join the discussion.
Thanks

**Comment by mattt-b** [comment]
It appears as though taxonomies may only be ordered alphabetically or by content https://gohugo.io/templates/taxonomy-templates/#order-taxonomies. Even their examples use [explicit taxonomies](https://gohugo.io/templates/taxonomy-templates/#display-a-single-piece-of-content-s-taxonomies).

You could keep [this construct](https://github.com/spookey/slick/blob/b0ced637cf093a544f290332a482decb030d4b2e/layouts/partials/post_meta.html#L7) and just move it into the config and keep the rest of the code the same. I think that would be an interesting solution because it has the side effect of making taxonomies hideable by making the array `[]`.

But if you're not happy with solutions, keep things in your vision. If desired, people could just overwrite that whole partial.

**Comment by spookey** [comment]
Thank you for your input @mattt-b.

Turns out this theme is the only one which handles taxonomies in that way (I was skimming through many other themes yesterday - all of them with tags do something like ``$.Params.tags``).

If I keep using ``$.Site.Taxonomies`` all I have is some array with lower cased strings, this looks ugly in the output.

Your proposed solution seems to be the most flexible. Also this is what already happens with the links in the menu (``menu.main``).
In the meantime, I will have a look if it is possible to use another menu (instead of a plain array of strings) for the post metadata.
