### ISSUE TITLE
The responsive grid elements don't seem to be working.

### ISSUE THREAD

**Issue by mason-bially** [spookey/slick#5]
For example if I compare the [slick demo site](https://themes.gohugo.io/theme/slick/) with the [temple demo site](https://aos.github.io/) it appears as if the responsive slick tags aren't working. Note how the slick content fills the whole window.

This doesn't appear to be intentional as the HTML on the slick site has the `pure-u-md-*` classes, they just don't appear to be working.

I did a brief look but I couldn't spot any obvious problems, so I'm not sure why it isn't working.

**Comment by mason-bially** [comment]
It appears to be a missing `media` attribute:

Temple:
```
<style type="text/css" media="screen">...</style>
```

Slick:
```
<link rel="stylesheet" href="https://themes.gohugo.io//theme/slick/assets/style.css">
```

**Comment by mason-bially** [comment]
I have no idea how to fix this in `postcss`

**Comment by spookey** [comment]
Hey, thanks for noticing.
This is a real issue that needs to be fixed. Don't know how this could slip through.

I was playing around with various breakpoints, did not work.
The issue is not in the html and it is no issue of ``purecss``.
It was the order how I bundled ``purecss`` together.

I have now a working example in my demo code, will commit it later and bump the version.
